// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-full grid grid-cols-[repeat(4,_auto)_auto_1fr] grid-rows-[1fr_25%] divide-x divide-y divide-border text-white\"><div class=\"p-4 col-span-4\"><svg viewBox=\"0 0 100 20\" preserveAspectRatio=\"xMinYMid meet\" class=\"w-full\"><text x=\"0\" y=\"0\" fill=\"white\" dominant-baseline=\"hanging\" font-family=\"Roboto\" font-size=\"20\" font-weight=\"bold\" textLength=\"100\" letter-spacing=\"0\" lengthAdjust=\"spacingAndGlyphs\">v3:cwlp/m</text></svg></div><div class=\"text-xs border-r-0 col-span-2\"><div class=\"py-4 px-8 border-b-main border-border\"><span class=\"uppercase\">About</span></div><div class=\"px-8 py-4 grid grid-cols-[min-content_1fr_10%_1fr]\"></div></div><div class=\"aspect-square bg-[url(/public/images/logo.webp)] bg-cover bg-center bg-no-repeat\"></div><a href=\"#\" class=\"aspect-square grid place-items-center hover:bg-discord transition-all duration-300\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("discord", "w-1/5 fill-current stroke-none").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</a> <a href=\"#\" class=\"aspect-square grid place-items-center hover:bg-black transition-all duration-300\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("github", "w-1/5 fill-current stroke-none").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</a><div class=\"aspect-square bg-[url(/public/images/wobble.png)] bg-cover bg-top bg-no-repeat\"></div><div class=\"aspect-square grid place-items-center hover:bg-red-500 hover:cursor-pointer transition-all duration-300\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("report", "w-1/5 fill-current stroke-none").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><a href=\"/login/discord\" class=\"relative grid place-items-center overflow-hidden group hover:bg-[#f2f2f2] transition-all duration-300\"><div class=\"absolute inset-0 flex justify-center pointer-events-none\"><div class=\"h-full grid grid-rows-3 grid-flow-col auto-cols-min divide-x-main divide-y-main divide-dashed divide-[#4f4f4f] group-hover:divide-solid\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for i := 0; i < 40; i++ {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"h-full aspect-square\"></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div><div class=\"relative z-10 bg-primary h-1/3 px-2 grid place-items-center border-b-main border-[#4f4f4f] border-dashed group-hover:border-solid group-hover:bg-[#f2f2f2] transition-all duration-300\"><span class=\"uppercase text-lg font-bold z-90 group-hover:text-black\">Login with <span class=\"text-discord\">Discord</span></span></div></a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Welcome").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
